import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar/navbar";
import Footer from "../components/footer/footer";
import { Lexend_Exa } from 'next/font/google'

const lexendExa = Lexend_Exa({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  variable: '--font-lexend-exa'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GORT ARCHIVE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lexendExa.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      style={{ overscrollBehavior: "none" }}
    >
      <body className="min-h-full flex flex-col">
        <NavBar/>
        {children}
        {/* <Footer/> */}
        {/* not sure if we need a footer will discuss later */}
        </body>
    </html>
  );
}
